### ISSUE TITLE
Pipeline decoder

### ISSUE THREAD

**Issue by ashton** [jaredramirez/rescript-json#2]
Hello, thanks for the awesome work!

I've seen that you based your work on `elm-json` and I'm a user of elm too. As elm, you've created `mapN` functions in order to map each field value to a specific decoder, but there is currently `map8` at max fields that we can map that way, in elm to solve this problem people create a workflow of a pipe decoder, using a function that instantiate a decoder from a value and then map every field in a pipe.

I saw that you have implemented `andMap` function and this should work just like pipe decoders in elm, but in elm we use the type itself as a constructor for the value using for example:

```elm
succeed(Type)
   |> required("field", string)
```

But with your library works a little different since we don't have a type constructor in rescript like we have in elm to give us a decoder of that specific type, so I was wondering how could we implement pipe decoders in rescript.

**Comment by jaredramirez** [comment]
Hey there!

Even though Rescript doesn't come out-of-the-box with constructor functions, it still works the same way. You just have to write your own function to construct your type:

```rescript
type t = { id: string, name: string }
let decoder: Json.Decode.t<t> = {
  open Json.Decode
  succeed((id, name) => { id: id, name: name })
  ->andMap(field("id", string))
  ->andMap(field("name", string))
}
```

**Comment by ashton** [comment]
I just find it in the documentation, maybe it was kind of dumb, but in the doc web page it wasn't clear for me that we could click on the links of the `Encode` and `Decode` modules to navigate through it's functions.

Sorry about that

**Comment by andremw** [comment]
@ashton I was looking for the same thing and I just noticed the links after you mentioned. I thought the docs we're just what's showing up in the main page.
Thanks for pointing out!

BTW, great job porting Elm's Json lib, Jared

**Comment by jaredramirez** [comment]
Added this to the new docs: https://rescript-json.jaredramirez.omg.lol/modules/json-decode#andmap
