### ISSUE TITLE
How to encode back to an inconsistent structure

### ISSUE THREAD

**Issue by andremw** [jaredramirez/rescript-json#6]
I'm planning on porting a big codebase from decco to rescript-json but one of the things I _might_ need to do is convert the values that decco generate for variants with payloads.

For example, a variant like this:

```rescript
@decco
type payload = {
  prop1: bool,
  prop2: string,
}

@decco
type t = Variant1(payload) | Variant2(payload)
```

is encoded by decco to:
`[ "Variant1", { "prop1": false, "prop2": "nice" } ]`

In case I really need to encode back to this structure, how could I do that? Is that possible in any way using rescript-json?

**Comment by andremw** [comment]
[This works](https://github.com/andremw/rescript-json/commit/30e367fb91d59afd18374992e590337ec709c632#diff-9825aed8c8420bf79fbc15f50d487f4db76be466f0ade5a911874f430337d686R36-R41). Is there anything to improve?

**Comment by jaredramirez** [comment]
Hey there!

This functionality could be achieved with the current API using `Json.Encode.array`. The idea is we have an array of `value`, then for the function argument of `array`, we use the identity function.

Here's what it would look like in practice:
```rescript
open Json.Encode
[ string("Variant1")
, object([ ( "prop1", bool(false) ), ( "prop2", string("nice") ) ])
]->array(v => v)
``` 

> This idea works with decoding too, just in reverse! You decode with the [value decoder](https://jaredramirez.github.io/rescript-json/gen/RescriptJson/Json/Decode/#val-value). You bring in the data to Rescript as `value`, then you can custom decode the 1st element as a `string`, the 2nd element as an `int` and so on. That said, `Json.Decode` has helper functions for this called [`tupleN`](https://jaredramirez.github.io/rescript-json/gen/RescriptJson/Json/Decode/#val-tuple2), as you probably already know!

If you'd find `tupleN` functions to be helpful to have in `Json.Encode`, I'd be open to a PR with those functions. For consistency though, I'd prefer that PR to implement `tuple2` through `tuple8`, just like `Json.Decode` has along with similar documentation.

**Comment by jaredramirez** [comment]
Closing this issue as this functionality is possible in `v1.0.3`

**Comment by jaredramirez** [comment]
Added this to the new docs: https://rescript-json.jaredramirez.omg.lol/modules/json-encode#array

**Comment by andremw** [comment]
This works for me, @jaredramirez ! Thank you!
